from __future__ import annotations

from dataclasses import dataclass
import re

@dataclass(frozen=True)
class StrategyDefinition:
    strategy_id: str
    name: str
    category: str
    horizon: int
    requires: tuple[str, ...] = ("xau_ohlc",)

GROUPS: dict[str, list[str]] = {'smc': ['Fair Value Gap (FVG) retracement continuation',
         'Inverse Fair Value Gap (IFVG) reversal',
         'FVG consequent-encroachment entry',
         'Breakaway FVG continuation',
         'Failed-FVG reclaim reversal',
         'Balanced Price Range (BPR) mean reversion',
         'Liquidity-void fill',
         'Volume-imbalance fill',
         'Order-block retest',
         'Order-block rejection continuation',
         'Breaker-block retest',
         'Mitigation-block retest',
         'Rejection-block reversal',
         'Propulsion-block continuation',
         'Liquidity-sweep reversal',
         'Liquidity-sweep reclaim continuation',
         'Equal-high/equal-low liquidity raid',
         'Previous-day high/low raid',
         'Previous-week high/low raid',
         'Previous-month high/low raid',
         'Session high/low raid',
         'Internal-liquidity → external-liquidity model',
         'External-liquidity → internal-liquidity retracement',
         'Draw on Liquidity (DOL) target model',
         'Optimal Trade Entry (OTE) retracement',
         'Premium/discount PD-array entry',
         'Equilibrium 50% reversion',
         'Market Structure Shift (MSS) retest',
         'Change of Character (CHOCH) retest',
         'Break of Structure (BOS) retest continuation',
         'Displacement-and-retracement continuation',
         'Change in State of Delivery (CISD) reversal',
         'SMT-divergence reversal',
         'Power of Three / Accumulation-Manipulation-Distribution',
         'Judas Swing',
         'ICT Silver Bullet',
         'ICT 2022 model',
         'Unicorn model',
         'Turtle Soup',
         'Market Maker Model',
         'MMXM model',
         'New Week Opening Gap (NWOG) fill',
         'New Day Opening Gap (NDOG) fill',
         'Midnight-open reversal',
         'Daily-open bias continuation',
         'ICT macro time-window liquidity sweep',
         'IPDA dealing-range model',
         'Quarterly-shift model',
         'Higher-timeframe PD-array alignment',
         'Liquidity sweep + displacement/FVG confirmation'],
 'price_action': ['Support/resistance bounce',
                  'Support/resistance breakout',
                  'Support/resistance breakout-retest',
                  'False-breakout reversal',
                  'Failed-breakdown reclaim',
                  'Trendline bounce',
                  'Trendline breakout',
                  'Trendline breakout-retest',
                  'Parallel-channel bounce',
                  'Parallel-channel breakout',
                  'Channel-overshoot reversal',
                  'Horizontal-range fade',
                  'Horizontal-range breakout',
                  'Range breakout-retest',
                  'Rectangle continuation breakout',
                  'Ascending-triangle breakout',
                  'Descending-triangle breakout',
                  'Symmetrical-triangle breakout',
                  'Triangle false-break reversal',
                  'Flag breakout',
                  'Pennant breakout',
                  'Wedge reversal',
                  'Wedge continuation breakout',
                  'Head-and-shoulders reversal',
                  'Double-top/double-bottom reversal',
                  'Triple-top/triple-bottom reversal',
                  'Rounding-top/rounding-bottom reversal',
                  'Cup-and-handle breakout',
                  'Saucer-base breakout',
                  'Diamond reversal',
                  'Broadening-formation breakout',
                  'Broadening-formation mean reversion',
                  'Megaphone false-break reversal',
                  '1-2-3 reversal',
                  'Ross Hook continuation',
                  'Swing Failure Pattern (SFP)',
                  'Key-reversal bar',
                  'Pin-bar rejection',
                  'Hammer/shooting-star reversal',
                  'Engulfing reversal',
                  'Outside-bar breakout',
                  'Inside-bar breakout',
                  'Inside-bar fakey',
                  'Mother-bar range breakout',
                  'Two-bar reversal',
                  'Three-bar reversal',
                  'Morning-star/evening-star reversal',
                  'Harami reversal',
                  'Tweezer-top/tweezer-bottom reversal',
                  'Doji rejection',
                  'Dragonfly/gravestone doji reversal',
                  'Kicker pattern',
                  'Piercing-line/dark-cloud reversal',
                  'Three-soldiers/three-crows reversal',
                  'Marubozu continuation',
                  'Railroad-tracks reversal',
                  'Tweezer + support/resistance confluence',
                  'Gap-and-go',
                  'Gap-fill fade',
                  'Breakaway-gap continuation',
                  'Exhaustion-gap reversal',
                  'Runaway/measuring-gap continuation',
                  'Island reversal',
                  'Opening-drive continuation',
                  'Failed-auction reversal',
                  'Micro double-top/double-bottom',
                  'First pullback after breakout',
                  'Second-entry pullback',
                  'Two-legged pullback',
                  'Three-push exhaustion',
                  'Parabolic blow-off reversal',
                  'Climactic reversal',
                  'Trend-exhaustion via shrinking range',
                  'Compression breakout',
                  'Impulse-correction-impulse continuation'],
 'trend': ['Single-moving-average trend filter + pullback',
           'Dual-moving-average crossover',
           'Triple-moving-average alignment',
           'Moving-average ribbon compression/expansion',
           'Moving-average slope continuation',
           'Price-vs-moving-average breakout',
           'Moving-average reclaim',
           'Moving-average rejection',
           'Moving-average envelope trend',
           'ADX trend-following',
           'DMI crossover trend',
           'Supertrend continuation',
           'Parabolic SAR trend-following',
           'Ichimoku Tenkan-Kijun cross',
           'Ichimoku Kumo breakout',
           'Ichimoku Kijun pullback',
           'Ichimoku Chikou-span confirmation',
           'Donchian-channel trend-follow',
           'Turtle breakout trend-follow',
           'Keltner-channel trend-follow',
           'ATR-channel trend-follow',
           'Linear-regression slope trend',
           'Linear-regression channel breakout',
           'MAMA/FAMA crossover trend',
           'Heikin-Ashi trend continuation',
           'Renko trend continuation',
           'Point-and-Figure breakout trend',
           'Aroon trend',
           'Vortex-indicator trend',
           'TRIX trend-follow',
           'TSI trend-follow',
           'MACD zero-line trend',
           'MACD signal-line trend',
           'PPO trend-follow',
           'R-squared trend-persistence model',
           'Guppy multiple-moving-average trend',
           'Alligator trend',
           'Fractal breakout trend',
           'Elder Impulse System',
           'Elder Triple Screen',
           'Darvas Box trend breakout',
           'Chandelier Exit trend-following',
           'N-bar higher-high/higher-low trend',
           'Swing-structure trend pullback',
           'Trend-acceleration breakout',
           'Trend-deceleration reversal/exit',
           'Breakout with trend-strength filter',
           'Regression-to-trend pullback',
           'Kaufman Adaptive Moving Average (KAMA) trend',
           'Ehlers Super Smoother trend'],
 'momentum': ['RSI centerline momentum',
              'RSI overbought/oversold reversal',
              'RSI failure swing',
              'RSI regular divergence',
              'RSI hidden divergence',
              'Stochastic crossover',
              'Stochastic extreme reversal',
              'Stochastic divergence',
              'Stochastic RSI momentum',
              'CCI zero-line momentum',
              'CCI extreme reversal',
              'CCI divergence',
              'Williams %R reversal',
              'Williams %R momentum',
              'Rate-of-Change threshold momentum',
              'Momentum-oscillator zero-line strategy',
              'MACD histogram acceleration',
              'MACD histogram divergence',
              'Awesome Oscillator zero-line strategy',
              'Awesome Oscillator saucer',
              'Accelerator Oscillator momentum',
              'Fisher Transform reversal',
              'Ultimate Oscillator divergence',
              'QQE momentum',
              'Relative Vigor Index crossover',
              'Coppock Curve momentum',
              'Chande Momentum Oscillator',
              'Chande Forecast Oscillator',
              'Qstick momentum',
              'Detrended Price Oscillator cycle turn',
              'Schaff Trend Cycle',
              'Know Sure Thing crossover',
              'Elder Bull/Bear Power divergence',
              'Force Index momentum',
              'Money Flow Index momentum',
              'Money Flow Index divergence',
              'Chaikin Oscillator momentum',
              'Balance of Power reversal',
              'Ease of Movement momentum',
              'DeMarker reversal',
              'Relative Momentum Index',
              'Dynamic Momentum Index',
              'Stochastic Momentum Index',
              'Laguerre RSI',
              'WaveTrend oscillator reversal'],
 'mean_reversion': ['Bollinger Band outer-band fade',
                    'Bollinger %B mean reversion',
                    'Bollinger W-bottom/M-top reversal',
                    'Bollinger band-walk exhaustion fade',
                    'Keltner-channel fade',
                    'Moving-average envelope fade',
                    'Donchian-channel fade',
                    'Rolling z-score mean reversion',
                    'Linear-regression residual mean reversion',
                    'Regression-channel edge fade',
                    'Volatility-scaled rolling-mean reversion',
                    'Median-price reversion',
                    'RSI(2) Connors-style short-term reversion',
                    'Consecutive up/down streak reversal',
                    'Gap-overextension reversion',
                    'ATR-overextension fade',
                    'True-range spike reversal',
                    'Realized-volatility spike fade',
                    'Volatility-cluster mean reversion',
                    'GARCH volatility mean reversion',
                    'Ornstein-Uhlenbeck residual mean reversion',
                    'Half-life optimized mean reversion',
                    'Hurst-exponent filtered mean reversion',
                    'Variance-ratio filtered mean reversion',
                    'Autocorrelation-filtered mean reversion',
                    'Kalman-filter fair-value reversion',
                    'Moving-average-distance percentile reversion',
                    'Rolling-percentile extreme reversion',
                    'Bollinger-Keltner overextension fade',
                    'Opening-drive failure fade',
                    'Post-breakout failure reversion',
                    'Failed-trend-day reversion',
                    'Close-to-open reversion',
                    'Overnight-move fade',
                    'Session-extension fade',
                    'Previous-close magnet reversion',
                    'Hilbert-cycle turning-point reversion',
                    'Ehlers Sinewave cycle reversal',
                    'MESA adaptive-cycle reversion',
                    'Hodrick-Prescott residual reversion',
                    'Spectral dominant-cycle reversion',
                    'Seasonal intraday mean reversion',
                    'Robust MAD-band mean reversion',
                    'Quantile-band mean reversion',
                    'Entropy-filtered mean reversion'],
 'breakout': ['Opening Range Breakout (ORB)',
              'Initial Balance breakout',
              'London opening-range breakout',
              'Asian-session range breakout',
              'New York opening-range breakout',
              'Tokyo-session range breakout',
              'Previous-day high/low breakout',
              'Previous-week high/low breakout',
              'Previous-month high/low breakout',
              'Overnight high/low breakout',
              'Session high/low breakout',
              'Inside-day breakout',
              'Outside-day continuation breakout',
              'NR4 breakout',
              'NR7 breakout',
              'Volatility-contraction breakout',
              'Bollinger Squeeze breakout',
              'TTM Squeeze breakout',
              'Keltner compression breakout',
              'ATR compression breakout',
              'Volatility-percentile breakout',
              'Realized-range expansion breakout',
              'ATR-multiple breakout from prior close',
              'Standard-deviation breakout',
              'Opening-gap breakout',
              'Gap continuation after consolidation',
              'News-range straddle breakout',
              'Post-news range breakout',
              'Economic-release first-minute breakout',
              'Pre-news compression breakout',
              'London-New York overlap breakout',
              'COMEX-open breakout',
              'Cash-market-open breakout',
              'Daily-settlement breakout',
              'Weekly-open breakout',
              'Monthly-open breakout',
              'Midnight-range breakout',
              'Rolling time-window breakout',
              'Range Expansion Index breakout',
              'Choppiness Index regime breakout',
              'ADX-expansion breakout',
              'Volatility-adjusted dynamic-threshold breakout',
              'Breakout-pullback continuation',
              'Multi-day consolidation breakout',
              'Three-touch level breakout'],
 'geometry': ['Fibonacci retracement continuation',
              'Fibonacci extension target breakout',
              'Fibonacci expansion measured move',
              'Fibonacci time-zone reversal',
              'Fibonacci fan reaction',
              'Fibonacci channel reaction',
              'Floor-pivot bounce',
              'Floor-pivot breakout',
              'Camarilla pivot reversal',
              'Camarilla pivot breakout',
              'Woodie pivot reversal',
              'Fibonacci pivot reversal',
              'DeMark pivot reversal',
              'Central Pivot Range breakout',
              'Central Pivot Range mean reversion',
              'Andrews Pitchfork median-line reversion',
              'Andrews Pitchfork outer-line breakout',
              'Schiff Pitchfork reversal',
              'Gann fan breakout',
              'Gann angle bounce',
              'Gann Square-of-Nine level reversal',
              'Murrey Math level reversal',
              'Gartley harmonic reversal',
              'Bat harmonic reversal',
              'Butterfly harmonic reversal',
              'Crab harmonic reversal',
              'Shark harmonic reversal',
              'Cypher harmonic reversal',
              '5-0 harmonic reversal',
              'AB=CD harmonic reversal'],
 'volume': ['Session VWAP trend continuation',
            'VWAP mean reversion',
            'VWAP breakout',
            'VWAP reclaim/rejection',
            'Anchored VWAP trend',
            'Anchored VWAP mean reversion',
            'VWAP deviation-band fade',
            'VWAP deviation-band breakout',
            'Multi-session VWAP confluence',
            'Rolling VWAP trend',
            'Volume Profile POC reversion',
            'POC breakout',
            'Developing-POC migration',
            'VAH/VAL rejection',
            'Value-area breakout',
            'Value-area rotation',
            'Low-volume-node breakout',
            'Low-volume-node rejection',
            'High-volume-node rotation',
            'High-volume-node breakout',
            'Volume-shelf breakout',
            'Composite-profile rotation',
            'Fixed-range Volume Profile breakout',
            'Previous-session profile-level reaction',
            'Naked-POC revisit',
            'Poor-high/poor-low repair',
            'Volume-spike reversal',
            'Volume-spike continuation',
            'OBV trend confirmation',
            'OBV divergence',
            'Accumulation/Distribution breakout',
            'Chaikin Money Flow trend',
            'Volume Oscillator breakout',
            'Positive/Negative Volume Index trend',
            'Volume Price Trend divergence'],
 'quant': ['Cointegration-spread mean reversion',
           'Kalman pairs mean reversion',
           'Dynamic hedge-ratio spread trading',
           'Gold-silver ratio mean reversion',
           'Gold-silver ratio momentum',
           'DXY-gold residual mean reversion',
           'Real-yield/gold residual mean reversion',
           'Multi-factor fair-value regression',
           'Ridge-regression directional model',
           'Lasso sparse-factor strategy',
           'Logistic-regression classifier',
           'Probit directional model',
           'Linear Discriminant Analysis strategy',
           'Quadratic Discriminant Analysis strategy',
           'k-nearest-neighbor regime strategy',
           'Support-vector-machine directional strategy',
           'Decision-tree strategy',
           'Random-forest directional strategy',
           'Gradient-boosted-tree strategy',
           'Naive Bayes directional strategy',
           'Hidden Markov regime-switching strategy',
           'Markov-chain transition strategy',
           'GARCH regime strategy',
           'Realized-volatility regime switching',
           'Hurst-exponent regime switch',
           'Variance-ratio trend/reversion switch',
           'Autocorrelation regime strategy',
           'Entropy-based regime strategy',
           'Permutation-entropy breakout filter',
           'PCA macro-factor strategy',
           'Kalman trend filter',
           'State-space local-trend strategy',
           'Fourier/spectral cycle strategy',
           'Wavelet multi-scale trend/reversion strategy',
           'Bayesian change-point strategy'],
 'macro': ['DXY inverse-momentum gold strategy',
           'DXY divergence gold reversal',
           'Real-yield inverse gold model',
           'Nominal-yield shock model',
           'Breakeven-inflation model',
           'Yield-curve slope regime model',
           'Fed-rate-decision surprise reaction',
           'FOMC-statement breakout',
           'CPI-surprise reaction',
           'Core-PCE-surprise reaction',
           'NFP-surprise reaction',
           'Unemployment-rate surprise reaction',
           'Retail-sales surprise reaction',
           'GDP-surprise reaction',
           'ISM-surprise reaction',
           'Geopolitical risk-off breakout',
           'VIX risk-off gold model',
           'Equity-index drawdown hedge model',
           'Crude-oil inflation-impulse model',
           'Copper/gold macro-ratio model',
           'COT managed-money momentum',
           'COT commercial-hedger contrarian',
           'Gold-ETF flow trend',
           'Central-bank purchase trend',
           'Month-of-year gold seasonality',
           'Day-of-week intraday seasonality',
           'Turn-of-month gold seasonality']}

_HORIZON = {
    "smc": 6,
    "price_action": 6,
    "trend": 12,
    "momentum": 8,
    "mean_reversion": 6,
    "breakout": 10,
    "geometry": 8,
    "volume": 8,
    "quant": 12,
    "macro": 12,
}

def _requirements(category: str, name: str) -> tuple[str, ...]:
    n = name.lower()
    if category == "volume":
        return ("xau_ohlc", "volume")
    if category == "quant":
        if "dxy" in n:
            return ("xau_ohlc", "dxy")
        if any(x in n for x in ("gold-silver", "cointegration", "pairs", "hedge-ratio", "real-yield", "multi-factor", "pca macro")):
            return ("xau_ohlc", "external_market")
        if any(x in n for x in (
            "ridge", "lasso", "logistic", "probit", "discriminant", "nearest-neighbor",
            "support-vector", "decision-tree", "random-forest", "gradient-boosted",
            "naive bayes", "hidden markov", "markov-chain", "bayesian change-point",
        )):
            return ("xau_ohlc", "model_training")
    if category == "macro":
        if n.startswith("dxy "):
            return ("xau_ohlc", "dxy")
        if any(x in n for x in ("month-of-year", "day-of-week", "turn-of-month")):
            return ("xau_ohlc",)
        return ("xau_ohlc", "macro_event_data")
    if "smt-divergence" in n:
        return ("xau_ohlc", "dxy")
    return ("xau_ohlc",)

STRATEGIES: tuple[StrategyDefinition, ...] = tuple(
    StrategyDefinition(
        strategy_id=f"S{i:03d}",
        name=name,
        category=category,
        horizon=_HORIZON[category],
        requires=_requirements(category, name),
    )
    for i, (category, name) in enumerate(
        ((category, name) for category, names in GROUPS.items() for name in names),
        start=1,
    )
)

if len(STRATEGIES) != 437:
    raise RuntimeError(f"Canonical strategy catalog must contain 437 strategies, found {len(STRATEGIES)}")
if len({s.strategy_id for s in STRATEGIES}) != 437 or len({s.name for s in STRATEGIES}) != 437:
    raise RuntimeError("Canonical strategy catalog contains duplicate ids or names")

BY_ID = {s.strategy_id: s for s in STRATEGIES}
BY_NAME = {s.name: s for s in STRATEGIES}

def slug(text: str) -> str:
    value = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return value or "strategy"
